### ISSUE TITLE
Tests action isn't working for PRs?

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ncbo/ontologies_api_ruby_client#14]
Hi, 
Within this repo, I have done three PRs where the tests worked in our forked environments but not here

## Example 
My [latest PR](https://github.com/ncbo/ontologies_api_ruby_client/pull/13) with the same code 
### In ontoportal-lirmm 
![image](https://user-images.githubusercontent.com/29259906/188523378-c3dc0e67-ea0e-486d-a74d-6cf0176b4394.png)

### In NCBO 

![image](https://user-images.githubusercontent.com/29259906/188523311-208279ec-29d3-4473-9e78-0ffa5b4d1258.png)

**Comment by syphax-bouazzouni** [comment]
Maybe the issue is with the `UT_APIKEY` in the [ruby.yml](https://github.com/ncbo/ontologies_api_ruby_client/blob/master/.github/workflows/ruby.yml) workflow
```yaml
env:
        UT_APIKEY: ${{ secrets.UT_APIKEY }}
```

@alexskr any thoughts about this?

**Comment by alexskr** [comment]
its hard to check whether APIKEY stored in the secrets is bad but I reset it anyway.  Are you able to re-run tests on your end?

**Comment by alexskr** [comment]
With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository so env variable is probably getting set to an empty value.  A new [extra check](https://github.com/ncbo/ontologies_api_ruby_client/commit/a52f30b8ab20d35569e404092dfd3831e57c415d) should catch this; however, unit test should first validate API key and provide more helpful feedback. 

Dependabot pull requests are treated as though they are from a fork which is the reason those are failing as well.

https://stackoverflow.com/questions/58737785/github-actions-empty-env-secrets

**Comment by syphax-bouazzouni** [comment]
Yeah it works, 
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/29259906/202656564-d8edfc32-7961-44b4-8496-9d0411637cbd.png">
